---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/PetPortalHosts

---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/PetPortalHosts/servers
  type: udm.Application

---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: !format Applications/PetPortalHosts/servers/%version%
  type: udm.ProvisioningPackage
  templates:
  ##########################################################################
  # Webserver Template
  - name: webserver
    type: template.overthere.SshHost
    instanceName: '{{project}}/TEST/webserver'
    childTemplates:
    - name: apache
      type: template.www.ApacheHttpdServer
      startCommand: systemctl start httpd
      stopCommand: systemctl stop httpd
      restartCommand: systemctl restart httpd
      defaultDocumentRoot: /var/www/html
      configurationFragmentDirectory: /etc/httpd/conf.d
    os: UNIX
    connectionType: SUDO
    address: '{{%outputVariables.webserver_public_dns%}}'
    username: ec2-user
    privateKeyFile: /opt/xebialabs/xl-deploy-server/conf/rbroker-us1.pem
    sudoUsername: root
  ##########################################################################
  # Appserver Template
  - name: appserver
    type: template.overthere.SshHost
    instanceName: '{{project}}/TEST/appserver'
    childTemplates:
    - name: jbosss
      type: template.jbossdm.StandaloneServer
      home: /opt/wildfly
      port: "9990"
      username: jboss
      password: admin
    - name: mysqldb
      type: template.sql.MySqlClient
      username: '{{DB_USERNAME}}'
      password: '{{DB_PASSWORD}}'
      mySqlHome: /usr
      databaseName: mysql
      additionalOptions: '--host='
    # - name: tomcat
    #   type: template.tomcat.Server
    #   childTemplates:
    #   - name: webapps
    #     type: template.tomcat.VirtualHost
    #   home: /var/lib/tomcat
    #   startCommand: systemctl start tomcat
    #   stopCommand: systemctl stop tomcat
    #   statusCommand: systemctl status tomcat
    #   startWaitTime: "10"
    #   stopWaitTime: "10"
    os: UNIX
    connectionType: SUDO
    address: '{{%outputVariables.appserver_public_dns%}}'
    username: ec2-user
    privateKeyFile: /opt/xebialabs/xl-deploy-server/conf/rbroker-us1.pem
    sudoUsername: root
  #############################################################################
  deployables:
  - name: servers
    type: terraform.Module
    boundTemplates:
    - !format Applications/PetPortalHosts/servers/%version%/webserver
    - !format Applications/PetPortalHosts/servers/%version%/appserver
    preScannedPlaceholders: true
    placeholders:
    - AWSRegion
    - AWS_SECRET_KEY
    - AWS_ACCESS_KEY
    fileEncodings:
      ".+\\.properties": ISO-8859-1
    environmentPath: '{{PROJECT}}/{{PROJECT}}-DEV'
    automaticDictionary: "true"
    dictionaryPath: '{{PROJECT}}-dic'
    generateCIsFromResources: "true"
    inputVariables:
      project: rrb-aws
    file: !file "artifacts/aws.ec2_instance.zip"

  - name: database
    type: terraform.Module
    preScannedPlaceholders: true
    placeholders:
    - AWSRegion
    - AWS_SECRET_KEY
    - AWS_ACCESS_KEY
    - MYSQL_USER
    - MYSQL_PASSWD
    fileEncodings:
      ".+\\.properties": ISO-8859-1
    environmentPath: '{{PROJECT}}/{{PROJECT}}-DEV'
    automaticDictionary: "true"
    dictionaryPath: '{{PROJECT}}-db-dic'
    generateCIsFromResources: "true"
    inputVariables:
      project: rrb-aws
    file: !file "artifacts/aws.rds.zip"
